---
- name: Do something with those instances
  hosts: all
  connection: winrm
#  gather_facts: False
 
  vars_files:
    - secret.yml

  tasks:

  - name: New Enable IIS on the servers
    win_feature:
      name: "Web-Server"
      state: present
      include_sub_features: yes
      include_management_tools: yes
      restart: yes
    register: iis_install

  - name: Reboot server if required
    win_reboot:
    when: iis_install.reboot_required is defined and iis_install.reboot_required == True

