---
- name: Do something with those instances
  hosts: all
  connection: winrm
#  gather_facts: False
  vars:
    nginx_version: "1.12.2"
 
  vars_files:
    - secret.yml

  tasks:
    - name: install nginx
      win_chocolatey:
        name: nginx
        state: present
        version: "{{ nginx_version }}"
    - name: install nssm
      win_chocolatey:
        name: nssm
        state: present
    - name: copy nginx conf file
      win_template: 
        src: nginx.conf.j2
        dest: "C:\ProgramData\chocolatey\lib\nginx\tools\nginx-{{ nginx_version }}\conf\nginx.conf"
    - name: install nginx as service
      win_nssm:
        name: nginx
        application: "C:\ProgramData\chocolatey\lib\nginx\tools\nginx-{{ nginx_version }}\nginx.exe"
        app_parameters_free_form: "-c C:\ProgramData\chocolatey\lib\nginx\tools\nginx-{{ nginx_version }}\conf\nginx.conf -p C:\ProgramData\chocolatey\lib\nginx\tools\nginx-{{ nginx_version }}"
        stdout_file: C:\nginx_out.txt
        stderr_file: C:\nginx_error.txt
        start_mode: auto
        state: started
        notify:
          - start nginx

#  - name: New Enable IIS on the servers
#    win_feature:
#      name: "Web-Server"
#      state: present
#      include_sub_features: yes
#      include_management_tools: yes
#    register: iis_install
#
#  - name: Reboot server if required
#    win_reboot:
#    when: iis_install.reboot_required is defined and iis_install.reboot_required == True

